#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

OpenFileIcon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAoZJREFUeNqMU89rE0EYfTs7SYyhSahpSjDKtjUUGipeGi+9"
    "qRR/HDwUBC/ixT9CREQEPXhTBA/iqQdFsR568CaopxpJpQVpaa1p2kYpMdDshnbnh99stykR"
    "BAce3+zsfO9735sZa/Y+gmFZuE7Bwf+NVa3x3Ey4DldoYXBk8sEtd+MbLKVxODOAeDoPZke7"
    "UznH7LOr9zqfSnV+sUS2QIlD2N3+CXdjEZ8+foDlXOzKtyIRuPLokRU5BEWFuNQHBEoKaN8H"
    "j6WRHh5HZlOjv3QNdiwGQRsUVatUKljwi4NlWSooKZeYJAUhbC0lOhACYsdFs9FAvVbDbrsN"
    "13XRarVw8867CUo+S5wFRnsRIiAwKgIlNN9pe/g8P4/v6+tYXF5GjPpvEOHjqSmcKRafLFQq"
    "V7g48MBW0ocUftiQRaQKjuNAkcN92Szi1P+FiQnskLpEIoGZcrnJ5QEBV4IUCLFnFrOJQGCT"
    "5Cd7etAi+StEZHwwKI2NQfg+45TTUaBD+YEAaUNQGwNGASVkSIGJOiSJ2HZI0KXAhwpbUIzB"
    "KKpWq0imUmh5HlIUTbJH82NEGBB8/QGM5EMPSL4MW2DMKBCBB6ZqX39/kJxLJoNoUwGfCNjt"
    "F4Ah8QWieyfghzBkKlBg0Gw2Ua/XYdOdZ5TMqIgh4BTjd18h/vQGkpocVXLPFHOMkiqNj44G"
    "p5DL5SBN/wSSQG/HMncjZogOEXrnVrHx5f3r7Vbjl29bNjRtMiZa+xUJnIwziNB9MPH31lbC"
    "2nfw3Elg8jQu0/U+35vND58olpyXb2bYo7njb1k02rYYk38/SeV5a7xrQWOa2p5er9VOrVVr"
    "l3o4ct7S0kPT7j+edfuPAAMA3U57lxQx/M8AAAAASUVORK5CYII=")
getOpenFileIconData = OpenFileIcon.GetData
getOpenFileIconImage = OpenFileIcon.GetImage
getOpenFileIconBitmap = OpenFileIcon.GetBitmap

#----------------------------------------------------------------------
NewFileIcon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAA2lpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tl"
    "dCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1l"
    "dGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUu"
    "MC1jMDYwIDYxLjEzNDc3NywgMjAxMC8wMi8xMi0xNzozMjowMCAgICAgICAgIj4gPHJkZjpS"
    "REYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgt"
    "bnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wUmlnaHRzPSJo"
    "dHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvcmlnaHRzLyIgeG1sbnM6eG1wTU09Imh0dHA6"
    "Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9tbS8iIHhtbG5zOnN0UmVmPSJodHRwOi8vbnMuYWRv"
    "YmUuY29tL3hhcC8xLjAvc1R5cGUvUmVzb3VyY2VSZWYjIiB4bWxuczp4bXA9Imh0dHA6Ly9u"
    "cy5hZG9iZS5jb20veGFwLzEuMC8iIHhtcFJpZ2h0czpNYXJrZWQ9IkZhbHNlIiB4bXBNTTpE"
    "b2N1bWVudElEPSJ4bXAuZGlkOjg5MTQzQUZFOTBCNjExREZCQTY2QjhCNkRGQjI3OEI2IiB4"
    "bXBNTTpJbnN0YW5jZUlEPSJ4bXAuaWlkOjg5MTQzQUZEOTBCNjExREZCQTY2QjhCNkRGQjI3"
    "OEI2IiB4bXA6Q3JlYXRvclRvb2w9IkFkb2JlIFBob3Rvc2hvcCBDUzMgV2luZG93cyI+IDx4"
    "bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ1dWlkOkFDMUYyRTgzMzI0QURG"
    "MTFBQUI4QzUzOTBEODVCNUIzIiBzdFJlZjpkb2N1bWVudElEPSJ1dWlkOkM5RDM0OTY2NEEz"
    "Q0REMTFCMDhBQkJCQ0ZGMTcyMTU2Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+"
    "IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+xVdBEgAAAXpJREFUeNqkk81Kw0AQ"
    "x2c3qaHNxYMI4sFD8VToSygUBC+C+Aw+RQs99AXEnkV6FPTgpQfpCxTSgl5sfQCR2EPTNh+7"
    "cSZpYhqTVnRgspvd//wys5llvu/Df0yNJuf1OjDGTnG6l6N9EkKMpBBAH71vtVYBUkoa9m8b"
    "jbbteeDgu4tiiWLDMOCm273EfYb+mqTyGEBiIZiPgRIB0nHAWSzAsiyYTqdw12y2cf8YpYeZ"
    "AA+D0LEKBgr6lqpCsVAADUfTNOGq04GjSuX62TAuXgaDn2dAAAJyDOacU00BhOykVgMqS9d1"
    "eOz3J5mH6LluCMAHZQApSLjJScfXAlgigzTkV4CghEQGSYiiKPkAN8ogKiEqKAGhdXcjAEXB"
    "n/guPIbwUJcDsO04AyqB2ioNoXXUZQNGvR7sVKsazdnyHKhlCUjd6BMEfWKa2sdwGANYdJkw"
    "6EAvl894qbS77vLI2ezdGo8fMO4tDdjGobjs9002x7jPFcBf7UuAAQD++8LAyPkpewAAAABJ"
    "RU5ErkJggg==")
getNewFileIconData = NewFileIcon.GetData
getNewFileIconImage = NewFileIcon.GetImage
getNewFileIconBitmap = NewFileIcon.GetBitmap

#----------------------------------------------------------------------
RunIcon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAAYJJREFUeNpi/P//PwMlgImBQsASGhqKIsDIyKgEpCyAmJcI"
    "/WdZ/v79iyzACzTAsqSkpFJUVET716/fDL9+/WQA0X/+/GX4/58RaAErAwsLBwMzMxtDW1tF"
    "JsufP3+QbTczNzeP+vLli/aHDx8YQHIwDLIIGW8Bgo0bNz5gYWNjg9uuoKBgXlVV5UWM369e"
    "vXrc1tb2NMvPnz9htpsGBgb6IrsIFzgJBHfu3DkhLCz8luXHjx8gMT5FRUU7ExMTi9+/f+OP"
    "NiYmhoULF+4AWnwGZDnLt2/fQIKWISEhXlDDCNl+5ubNm8eBLv4EjkagAfxKSkoOZmZmpr9+"
    "/cKrmZWVlWHmzJl7vn//fgKeDoAhbh8dHe3+9etXgrYfOnTo/LVr144BDfj45s0bBpAels+f"
    "P5toaWkpsbCw4NX8/v37jz09PUeePn16GKgHEfWcnJyZwDCQIybqgPF/GRhOV4HMd0D8Foi/"
    "MQIJLiDmAXmHyOT/D4i/gzQD8W/GAc+NAAEGAH6Du6zbRlpcAAAAAElFTkSuQmCC")
getRunIconData = RunIcon.GetData
getRunIconImage = RunIcon.GetImage
getRunIconBitmap = RunIcon.GetBitmap

#-----------------------------------------------------------------------
star = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAGXRFWHRTb2Z0d2FyZQBBZG9i"
    "ZSBJbWFnZVJlYWR5ccllPAAAApdJREFUeNpsUk1oE1EQnrfZpJsmadIktNiGVougwVZblEIP"
    "9WgPKkIRwYP1onj2JggeREQvil6KIogWPYngXwWlf1ITEdRLa8TWWjTBltb+JZv9y9vnTJK1"
    "NnXg481+b2Z2Zr7HoGx72xjcugyV1lc+7zvEmTcSfMhJAP0W9PUyYK8HWPHCLQP4/ZsKXC+f"
    "Z/8lx2YZ7A6Joi87pFVAWEj8ZaDJ69+2kxwt970Jjx/kFzDOSd5QgCynAvh8JZ8x6ArW748B"
    "CMiufu8SolRAVTe2KFX2rOulvyC6w/WdsXBdZ4x84uiu0jYV4BxRgGaPEovLkgjJkh3yKI1x"
    "4uiu0mRsbbCSpH3URNsbdHUWJxAQCLc2rC5n+uE/xl4NuHBOOFdb19a1o+N0XJYlLzeXMNEG"
    "K58u/UWpK34zVxWYhqp9+/w4tfJ7JolXV6iAM8pRl6ycaon3xsPR5piuZUCzcqCbGu7DQnUC"
    "YKwuphcy71I2t+5g/COE7RRwjLq52LKn94gBc2Eh1uUSpmvp15fxJ+heQKQ3yaiqAt+BSCOy"
    "jfoc8/o36pXLc7awwLNuN0sjUO7SA5QOnOCQyXBYWbGpiIdzqT1Sawar3Rr4PDb43BZUyxpE"
    "a60g56ydYiiWcii3KOPV22X5OLQGQ75IlZyTuGmbiaGpycTw9CQ3NVNxG1JNUIlQDMVSDllx"
    "AYvLuA0cd3szHGraGujJq4YxPvIzlc2aN1W1kJiZXospiqsKFZLn5/Wpp8PwMfFpvQB14f06"
    "C8Gebjip5QuRiYm19y/HxPlrd+Ht8xFIcS6SqOkW0+ABTbPhxj1IOu+OlkjbqEZEJQYdo0nr"
    "wcNnMGiYkEeuhgR4MQpLQ0m4dPywdXDfLjhGsdQ4wvgjwABxPCwzsru8RAAAAABJRU5ErkJg"
    "gg==")
getstarData = star.GetData
getstarImage = star.GetImage
getstarBitmap = star.GetBitmap